site_name: pytest_patterns
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/pytest-patterns
docs_dir: .
site_dir: ../site
nav:
    - Home: index.md
    - Examples:
      - Data science benchmark: examples/data_science_benchmark/index.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
